//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HLCMPruebaLibrosEntities : DbContext
    {
        public HLCMPruebaLibrosEntities()
            : base("name=HLCMPruebaLibrosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autor> Autors { get; set; }
        public virtual DbSet<Editorial> Editorials { get; set; }
        public virtual DbSet<Libro> Libroes { get; set; }
    
        public virtual int LibroAdd(string titulo, Nullable<int> anioPublicacion, Nullable<int> idAutor, Nullable<int> idEditorial)
        {
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            var anioPublicacionParameter = anioPublicacion.HasValue ?
                new ObjectParameter("AnioPublicacion", anioPublicacion) :
                new ObjectParameter("AnioPublicacion", typeof(int));
    
            var idAutorParameter = idAutor.HasValue ?
                new ObjectParameter("IdAutor", idAutor) :
                new ObjectParameter("IdAutor", typeof(int));
    
            var idEditorialParameter = idEditorial.HasValue ?
                new ObjectParameter("IdEditorial", idEditorial) :
                new ObjectParameter("IdEditorial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LibroAdd", tituloParameter, anioPublicacionParameter, idAutorParameter, idEditorialParameter);
        }
    
        public virtual int LibroDeleteAutor(Nullable<int> idAutor)
        {
            var idAutorParameter = idAutor.HasValue ?
                new ObjectParameter("IdAutor", idAutor) :
                new ObjectParameter("IdAutor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LibroDeleteAutor", idAutorParameter);
        }
    
        public virtual int LibroDeleteEditorial(Nullable<int> idEditorial)
        {
            var idEditorialParameter = idEditorial.HasValue ?
                new ObjectParameter("IdEditorial", idEditorial) :
                new ObjectParameter("IdEditorial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LibroDeleteEditorial", idEditorialParameter);
        }
    
        public virtual ObjectResult<LibroGetAll_Result> LibroGetAll(string nombreAutor, string titulo, Nullable<int> anioPublicacion, string nombreEditorial)
        {
            var nombreAutorParameter = nombreAutor != null ?
                new ObjectParameter("NombreAutor", nombreAutor) :
                new ObjectParameter("NombreAutor", typeof(string));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            var anioPublicacionParameter = anioPublicacion.HasValue ?
                new ObjectParameter("AnioPublicacion", anioPublicacion) :
                new ObjectParameter("AnioPublicacion", typeof(int));
    
            var nombreEditorialParameter = nombreEditorial != null ?
                new ObjectParameter("NombreEditorial", nombreEditorial) :
                new ObjectParameter("NombreEditorial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LibroGetAll_Result>("LibroGetAll", nombreAutorParameter, tituloParameter, anioPublicacionParameter, nombreEditorialParameter);
        }
    
        public virtual ObjectResult<LibroGetById_Result> LibroGetById(Nullable<int> idLibro)
        {
            var idLibroParameter = idLibro.HasValue ?
                new ObjectParameter("IdLibro", idLibro) :
                new ObjectParameter("IdLibro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LibroGetById_Result>("LibroGetById", idLibroParameter);
        }
    }
}
